name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  noetic-deploy:
    if: contains(github.event.head_commit.message, 'noetic')
    name: noetic-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${GITHUB_WORKSPACE}/ros/generate_images.bash -d ${GITHUB_WORKSPACE}/ros/noetic/ -u
       
  foxy-deploy:
    if: contains(github.event.head_commit.message, 'foxy')
    name: foxy-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${GITHUB_WORKSPACE}/ros2/generate_images.bash -d ${GITHUB_WORKSPACE}/ros2/foxy/ -u
      
  galactic-deploy:
    if: contains(github.event.head_commit.message, 'galactic')
    name: galactic-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${GITHUB_WORKSPACE}/ros2/generate_images.bash -d ${GITHUB_WORKSPACE}/ros2/galactic/ -u
      
  humble-deploy:
    if: contains(github.event.head_commit.message, 'humble')
    name: humble-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${GITHUB_WORKSPACE}/ros2/generate_images.bash -d ${GITHUB_WORKSPACE}/ros2/humble/ -u

  iron-deploy:
    if: contains(github.event.head_commit.message, 'iron')
    name: iron-deploy
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ${GITHUB_WORKSPACE}/ros2/generate_images.bash -d ${GITHUB_WORKSPACE}/ros2/iron/ -u
