name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
       ${GITHUB_WORKSPACE}/ros/generate_images.bash -d ${GITHUB_WORKSPACE}/ros/noetic/ -u
       docker images
