name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         chmod +x ${GITHUB_WORKSPACE}/ros/generate_images.bash
         ${GITHUB_WORKSPACE} /ros/generate_images.bash -d noetic/ -u
         chmod +x ${GITHUB_WORKSPACE} /ros2/generate_images.bash
         ${GITHUB_WORKSPACE} /ros2/generate_images.bash -d noetic/ -u
